name: CI for LABWORK2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up GCC
        run: sudo apt-get install -y g++

      - name: install Google Test
        run: |
          sudo apt-get install -y libgtest-dev libgmock-dev make

      - name: Build with Makefile
        run: make

  run_tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ make libgtest-dev libgmock-dev

      - name: Build Google Tests
        run: make test

      - name: Run Tests
        run: ./test-LABWORK2
